---
title: "Proyecto analisis exploratorio y clustering"
author: "Andres Quinto, Mirka Monzon, Oscar De Leon, Oscar Ramos, Diego Crespo"
date: "26/03/2022"
output: 
  html_document:
    code_folding: hide
    word_document: default
    pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(foreign)
#Lectura y conversion de los .SAV

# Comentados los savs que ya fueron convertidos en .csv
# write.csv(X2011, 'X2011.csv')
# write.csv(X2012, 'X2012.csv')
# write.csv(X2013, 'X2013.csv')
# write.csv(base1, 'base1.csv')
# write.csv(X2016, 'X2016.csv')
# write.csv(matri2014, 'matri2014 .csv')
# write.csv(matri2015 , 'matri2015 .csv')
# write.csv(matri2016 , 'matri2016 .csv')
# 

datos2011 <- read_sav("D:\\Universidad\\mineria de datos\\ProyectoMineria1\\Proyecto-analisis-y-clustering\\SAVS\\20111.sav")
datos2012 <- read_sav("D:\\Universidad\\mineria de datos\\ProyectoMineria1\\Proyecto-analisis-y-clustering\\SAVS\\20122.sav")
datosNacim2011 <- read_sav("D:\\Universidad\\mineria de datos\\ProyectoMineria1\\Proyecto-analisis-y-clustering\\SAVS\\2011N.sav")
datosNacim2012 <- read_sav("D:\\Universidad\\mineria de datos\\ProyectoMineria1\\Proyecto-analisis-y-clustering\\SAVS\\nacim2012.sav")
datos2019 <- read_sav("D:\\Universidad\\mineria de datos\\ProyectoMineria1\\Proyecto-analisis-y-clustering\\SAVS\\2019.sav")

#---------------------Modificaciones 2011----------------------
#Crear columnas en dataset 2011 NUNUHO, NUNUMU
NUNUHO <- rnorm(nrow(datos2011))
datos2011 <- cbind(datos2011,NUNUHO)
datos2011$NUNUHO <- "None"
NUNUMU <- rnorm(nrow(datos2011))
datos2011 <- cbind(datos2011, NUNUMU)
datos2011$NUNUMU <- "None"
#Poner todas en uppercase 2011
cnames <- colnames(datos2011)
mayu2011 = c()
for (i in 1:length(cnames)){
  mayu2011[i] <- toupper(cnames[i])  
}
colnames(datos2011)<-mayu2011
#cambiar AREAG por AREAGOCU, OCUHOM, OCUMUJ, PUEHOM, PUEMUJ
cnames <- colnames(datos2011)
nombresN = c()
for(i in 1:length(cnames)){
  if(cnames[i] == "AREAG"){
    nombresN[i] <- "AREAGOCU"
  }
  else if(cnames[i] == "OCUHOM"){
    nombresN[i] <- "CIUOHOM"
  }
  else if(cnames[i] == "OCUMUJ"){
    nombresN[i] <- "CIUOMUJ"
  }
  else if(cnames[i] == "GETHOM"){
    nombresN[i] <- "PUEHOM"
  }
  else if(cnames[i] == "GETMUJ"){
    nombresN[i] <- "PUEMUJ"
  }
  else{
    nombresN[i] <- cnames[i]
  }
}
colnames(datos2011) <- nombresN

#-------------------------Modificaciones 2012------------------------

#Crear columnas en dataset 2012 AÑOOCU, NUNUHO, NUNUMU
AÑOOCU <- rnorm(nrow(datos2012))
datos2012 <- cbind(datos2012, AÑOOCU)
datos2012$AÑOOCU <- "None"
NUNUHO <- rnorm(nrow(datos2012))
datos2012 <- cbind(datos2012,NUNUHO)
datos2012$NUNUHO <- "None"
NUNUMU <- rnorm(nrow(datos2012))
datos2012 <- cbind(datos2012, NUNUMU)
datos2012$NUNUMU <- "NA"
#View(datos2012)
#cambiar AREAG por AREAGOCU, OCUHOM, OCUMUJ, PUEHOM, PUEMUJ
cnames <- colnames(datos2012)
nombresN = c()
for(i in 1:length(cnames)){
  if(cnames[i] == "AREAG"){
    nombresN[i] <- "AREAGOCU"
  }
  else if(cnames[i] == "OCUHOM"){
    nombresN[i] <- "CIUOHOM"
  }
  else if(cnames[i] == "OCUMUJ"){
    nombresN[i] <- "CIUOMUJ"
  }
  else if(cnames[i] == "GETHOM"){
    nombresN[i] <- "PUEHOM"
  }
  else if(cnames[i] == "GETMUJ"){
    nombresN[i] <- "PUEMUJ"
  }
  else{
    nombresN[i] <- cnames[i]
  }
}
colnames(datos2012) <- nombresN
#datos2012$AÑOOCU <- ifelse(datos2012$AÑOOCU == 'None', 2012, datos2012$AÑOOCU)

#-------------------------Modificaciones 2019------------------------
#Agregar columna areagocu
#Poner todas en uppercase 2019
AREAGOCU <- rnorm(nrow(datos2019))
datos2019 <- cbind(datos2019, AREAGOCU)
datos2019$AREAGOCU <- "None"

#-------------------------Modificaciones Nacimientos 2019------------------------
cnames <- colnames(datosNacim2019)
mayu2011 = c()
for (i in 1:length(cnames)){
  mayu2011[i] <- toupper(cnames[i])  
}
colnames(datosNacim2019)<-mayu2011
#CAMBIOS DE BASE NACIMIENTOS 2011 PARA QUE SEA SIMILAR A 2019
#Poner todas en uppercase 2011
cnames <- colnames(datosNacim2011)
mayu2011 = c()
for (i in 1:length(cnames)){
  mayu2011[i] <- toupper(cnames[i])  
}
colnames(datosNacim2011)<-mayu2011

#Cambiar MUPNAP a MUNPNAP
cnames <- colnames(datosNacim2011)
nombresN = c()
for(i in 1:length(cnames)){
  if(cnames[i] == "MUPNAP"){
    nombresN[i] <- "MUNPNAP"
  }
}
#AGREGAR LAS COLUMNAS FALTANTES Y LLENARLAS DE NONE
TIPOINS <- rnorm(nrow(datosNacim2011))
datosNacim2011 <- cbind(datosNacim2011, TIPOINS)
datosNacim2011$TIPOINS <- "None"

VIAPAR <- rnorm(nrow(datosNacim2011))
datosNacim2011 <- cbind(datosNacim2011, VIAPAR)
datosNacim2011$VIAPAR <- "None"

PAISREP <- rnorm(nrow(datosNacim2011))
datosNacim2011 <- cbind(datosNacim2011, PAISREP)
datosNacim2011$PAISREP <- "None"

PUEBLOPP <- rnorm(nrow(datosNacim2011))
datosNacim2011 <- cbind(datosNacim2011, PUEBLOPP)
datosNacim2011$PUEBLOPP <- "None"

PAISNACP <- rnorm(nrow(datosNacim2011))
datosNacim2011 <- cbind(datosNacim2011, PAISNACP)
datosNacim2011$PAISNACP <- "None"

PAISREM <- rnorm(nrow(datosNacim2011))
datosNacim2011 <- cbind(datosNacim2011, PAISREM)
datosNacim2011$PAISREM <- "None"

PUEBLOPM <- rnorm(nrow(datosNacim2011))
datosNacim2011 <- cbind(datosNacim2011, PUEBLOPM)
datosNacim2011$PUEBLOPM <- "None"

PAISNACM <- rnorm(nrow(datosNacim2011))
datosNacim2011 <- cbind(datosNacim2011, PAISNACM)
datosNacim2011$PAISNACM <- "None"
#ELIMINAMOS LAS COLUMNAS EXTRAS

datosNacim2011 = datosNacim2011[,!(names(datosNacim2011) %in% c("AREAG","GRETNP", "NACIOP","GRUPETMA","NACIOM"))]

#CAMBIOS DE BASE NACIMIENTOS 2012 PARA QUE SEA SIMILAR A 2019
#Poner todas en uppercase 2012
cnames <- colnames(datosNacim2012)
mayu2011 = c()
for (i in 1:length(cnames)){
  mayu2011[i] <- toupper(cnames[i])  
}
colnames(datosNacim2012)<-mayu2011

#Cambiar MUPNAP a MUNPNAP
cnames <- colnames(datosNacim2012)
nombresN = c()
for(i in 1:length(cnames)){
  if(cnames[i] == "MUPNAP"){
    nombresN[i] <- "MUNPNAP"
  }
}
#AGREGAR LAS COLUMNAS FALTANTES Y LLENARLAS DE NONE
TIPOINS <- rnorm(nrow(datosNacim2012))
datosNacim2012 <- cbind(datosNacim2012, TIPOINS)
datosNacim2012$TIPOINS <- "None"

VIAPAR <- rnorm(nrow(datosNacim2012))
datosNacim2012 <- cbind(datosNacim2012, VIAPAR)
datosNacim2012$VIAPAR <- "None"

PAISREP <- rnorm(nrow(datosNacim2012))
datosNacim2012 <- cbind(datosNacim2012, PAISREP)
datosNacim2012$PAISREP <- "None"

PUEBLOPP <- rnorm(nrow(datosNacim2012))
datosNacim2012 <- cbind(datosNacim2012, PUEBLOPP)
datosNacim2012$PUEBLOPP <- "None"

PAISNACP <- rnorm(nrow(datosNacim2012))
datosNacim2012 <- cbind(datosNacim2012, PAISNACP)
datosNacim2012$PAISNACP <- "None"

PAISREM <- rnorm(nrow(datosNacim2012))
datosNacim2012 <- cbind(datosNacim2012, PAISREM)
datosNacim2012$PAISREM <- "None"

PUEBLOPM <- rnorm(nrow(datosNacim2012))
datosNacim2012 <- cbind(datosNacim2012, PUEBLOPM)
datosNacim2012$PUEBLOPM <- "None"

PAISNACM <- rnorm(nrow(datosNacim2012))
datosNacim2012 <- cbind(datosNacim2012, PAISNACM)
datosNacim2012$PAISNACM <- "None"
#ELIMINAMOS LAS COLUMNAS EXTRAS

datosNacim2012 = datosNacim2012[,!(names(datosNacim2012) %in% c("AREAG","GRETNP", "NACIOP","GRUPETMA","NACIOM"))]
```

```{r}
library(haven)
library(foreign)

datos2013 <- read_sav("./SAVS/2013M.sav")

#-------------------------Modificaciones 2013 matrimonios------------------------
#columnas a crear para año 2013: NUNUHO, NUNUMU
#no hay columnas para cambiar 

#NUNUHO
NUNUHO <- rnorm(nrow(datos2013))
datos2013 <- cbind(datos2013,NUNUHO)
datos2013$NUNUHO <- "None"

#NUNUMU
NUNUMU <- rnorm(nrow(datos2013))
datos2013 <- cbind(datos2013, NUNUMU)
datos2013$NUNUMU <- "NA"

```

```{r}
library(haven)
library(foreign)

datos2014 <- read_sav("./SAVS/2014M.sav")

#-------------------------Modificaciones 2014 matrimonios------------------------
#columnas a crear para año 2014: NUNUHO, NUNUMU
#no hay comunas para cambiar 

#NUNUHO
NUNUHO <- rnorm(nrow(datos2014))
datos2014 <- cbind(datos2014,NUNUHO)
datos2014$NUNUHO <- "None"

#NUNUMU
NUNUMU <- rnorm(nrow(datos2014))
datos2014 <- cbind(datos2014, NUNUMU)
datos2014$NUNUMU <- "NA"

#Agregar columna anoocu
AÑOOCU <- rnorm(nrow(datos2014))
datos2014 <- cbind(datos2014, AÑOOCU)
datos2014$AÑOOCU <- "None"
```

```{r}
library(haven)
library(foreign)

datosN2013 <- read_sav("./SAVS/2013N.sav")

#-------------------------Modificaciones 2013 nacimientos------------------------
#columnas a crear para año 2013: TIPOINS, AÑOOCU, VIAPAR 
#columnas a cambiar: CIUPAD - OCUPAP / CIUMAD - OCUPAM
#columnas a borrar: NACIOP, ESCOLAP, NACIOM 

#TIPOINS
TIPOINS <- rnorm(nrow(datosN2013))
datosN2013 <- cbind(datosN2013,TIPOINS)
datosN2013$TIPOINS <- "None"

#AÑOOCU
AÑOOCU <- rnorm(nrow(datosN2013))
datosN2013 <- cbind(datosN2013,AÑOOCU)
datosN2013$AÑOOCU <- "None"

#VIAPAR
VIAPAR <- rnorm(nrow(datosN2013))
datosN2013 <- cbind(datosN2013,VIAPAR)
datosN2013$VIAPAR <- "None"

#cambio de nombre de columnas
cnames <- colnames(datosN2013)
nombresN = c()
for(i in 1:length(cnames)){
  if(cnames[i] == "CIUPAD"){
    nombresN[i] <- "OCUPAP"
  }
  else if(cnames[i] == "CIUMAD"){
    nombresN[i] <- "OCUPAM"
  }
  else{
    nombresN[i] <- cnames[i]
  }
}
colnames(datosN2013) <- nombresN

#drop NACIOP
datosN2013$NACIOP <- NULL

#drop ESCOLAP
datosN2013$ESCOLAP <- NULL

#drop NACIOM
datosN2013$NACIOM <- NULL
```

```{r}
library(haven)
library(foreign)

datosN2014 <- read_sav("./SAVS/2014N.sav")

#-------------------------Modificaciones 2014 nacimientos------------------------
#columnas a crear para año 2013: TIPOINS, AÑOOCU, VIAPAR, OCUPAP
#columnas a cambiar: NA
#columnas a borrar: CIUMAD  

#TIPOINS
TIPOINS <- rnorm(nrow(datosN2014))
datosN2014 <- cbind(datosN2014,TIPOINS)
datosN2014$TIPOINS <- "None"

#AÑOOCU
AÑOOCU <- rnorm(nrow(datosN2014))
datosN2014 <- cbind(datosN2014,AÑOOCU)
datosN2014$AÑOOCU <- "None"

#VIAPAR
VIAPAR <- rnorm(nrow(datosN2014))
datosN2014 <- cbind(datosN2014,VIAPAR)
datosN2014$VIAPAR <- "None"

#OCUPAP
OCUPAP <- rnorm(nrow(datosN2014))
datosN2014 <- cbind(datosN2014,OCUPAP)
datosN2014$OCUPAP <- "None"

#drop CIUMAD
datosN2014$CIUMAD <- NULL
```


```{r}
library(haven)
library(foreign)

datos2013 <- read_sav("./SAVS/2013M.sav")

#-------------------------Modificaciones 2013------------------------
#columnas a crear para año 2013: NUNUHO, NUNUMU
#no hay columnas para cambiar 
#columnas por borrar: x

#NUNUHO
NUNUHO <- rnorm(nrow(datos2013))
datos2013 <- cbind(datos2013,NUNUHO)
datos2013$NUNUHO <- "None"

#NUNUMU
NUNUMU <- rnorm(nrow(datos2013))
datos2013 <- cbind(datos2013, NUNUMU)
datos2013$NUNUMU <- "NA"

#Agregar columna anoocu
AÑOOCU <- rnorm(nrow(datos2013))
datos2013 <- cbind(datos2013, AÑOOCU)
datos2013$AÑOOCU <- "None"
```



```{r}
library(haven)
library(foreign)

datos2015 <- read_sav("./SAVS/2015M.sav")

#NO FUE NECESARIO REALIZAR CAMBIOS 

```


```{r}
library(haven)
library(foreign)

datosNacim2015 <- read_sav("./SAVS/2015N.sav")

#NO FUE NECESARIO REALIZAR CAMBIOS

```


```{r}
library(haven)
library(foreign)

datosNacim2016 <- read_sav("./SAVS/2016N.sav")

#NO FUE NECESARIO REALIZAR CAMBIOS

```

```{r}
library(haven)
library(foreign)

datos2016 <- read_sav("./SAVS/2016M.sav")

#NO FUE NECESARIO REALIZAR CAMBIOS

```

```{r}
library(haven)
library(foreign)

datosNacim2019 <- read_sav("./2019N.sav")

#NO FUE NECESARIO REALIZAR CAMBIOS

```


```{r}
#UNIMOS LAS BASES DE MATRIMONIOS DEL 2011 AL 2016
#---------- Ya con todas las bases con las mismas columnas (cant columnas y nombres) podemos unirlas 

install.packages("sf")
library(dplyr)
library(sf)
#------------------------Unión de las bases-------------------------
datos2011 <- datos2011 %>%
  mutate_if(is.labelled,list(as_factor))
datos2012 <- datos2012 %>%
  mutate_if(is.labelled,list(as_factor))
datos2013 <- datos2013 %>%
  mutate_if(is.labelled,list(as_factor))
datos2014 <- datos2014 %>%
  mutate_if(is.labelled,list(as_factor))
datos2015 <- datos2015 %>%
  mutate_if(is.labelled,list(as_factor))
datos2016 <- datos2016 %>%
  mutate_if(is.labelled,list(as_factor))

l = list(datos2011,datos2012,datos2013,datos2014,datos2015,datos2016)
datosMatrimonio <- do.call("rbind",l)
datosMatrimonio$EDADHOM <- as.numeric(factor(datosMatrimonio$EDADHOM))
datosMatrimonio$EDADMUJ <- as.numeric(factor(datosMatrimonio$EDADMUJ))

datosMatrimonio$ESCHOM <- ifelse(datosMatrimonio$ESCHOM == "DIversificado","Diversificado",datosMatrimonio$ESCHOM)
datosMatrimonio$ESCHOM <- ifelse(datosMatrimonio$ESCHOM == "Post Grado","Universitario",datosMatrimonio$ESCHOM)
datosMatrimonio$ESCHOM <- ifelse(datosMatrimonio$ESCHOM == "Postgrado","Universitario",datosMatrimonio$ESCHOM)
datosMatrimonio$ESCMUJ <- ifelse(datosMatrimonio$ESCMUJ == "DIversificado","Diversificado",datosMatrimonio$ESCMUJ)
datosMatrimonio$ESCMUJ <- ifelse(datosMatrimonio$ESCMUJ == "Post Grado","Universitario",datosMatrimonio$ESCMUJ)
datosMatrimonio$ESCMUJ <- ifelse(datosMatrimonio$ESCMUJ == "Postgrado","Universitario",datosMatrimonio$ESCMUJ)


datosMatrimonio$DEPOCU <- levels(datosMatrimonio$DEPOCU)[datosMatrimonio$DEPOCU]
datosMatrimonio$DEPOCU <- ifelse(datosMatrimonio$DEPOCU == "Totonicapán","Totonicapan",datosMatrimonio$DEPOCU)
datosMatrimonio$DEPOCU <- ifelse(datosMatrimonio$DEPOCU == "Petén","Peten",datosMatrimonio$DEPOCU)
datosMatrimonio$DEPOCU <- factor(datosMatrimonio$DEPOCU)


datosMatrimonio$PUEHOM <- levels(datosMatrimonio$PUEHOM)[datosMatrimonio$PUEHOM]
datosMatrimonio$PUEMUJ <- levels(datosMatrimonio$PUEMUJ)[datosMatrimonio$PUEMUJ]
datosMatrimonio$PUEHOM <- ifelse(datosMatrimonio$PUEHOM == "No Indigena", "No indigena",datosMatrimonio$PUEHOM)
datosMatrimonio$PUEMUJ <- ifelse(datosMatrimonio$PUEMUJ == "No Indigena", "No indigena",datosMatrimonio$PUEMUJ)
datosMatrimonio$PUEHOM <- factor(datosMatrimonio$PUEHOM)
datosMatrimonio$PUEMUJ <- factor(datosMatrimonio$PUEMUJ)

```

